[actions.Run]
name = "Run"
command = "./script/build_and_run.sh"

[actions."Run Android"]
name = "Run Android"
command = "./script/build_and_run.sh --android"

[actions."Run Web"]
name = "Run Web"
command = "./script/build_and_run.sh --web"
